// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanejaAi.Data;

#nullable disable

namespace PlanejaAi.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PlanejaAi.Models.CategoriaServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cat_data_cadastro");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cat_nome");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("categorias_servico");
                });

            modelBuilder.Entity("PlanejaAi.Models.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("check_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("check_concluido");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("check_descricao");

                    b.Property<int>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("even_id");

                    b.HasKey("Id");

                    b.ToTable("checklist");
                });

            modelBuilder.Entity("PlanejaAi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("clien_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_cidade");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("clien_data");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("clien_documento");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_email");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("clien_nome");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_numero");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("clien_status");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_telefone");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext")
                        .HasColumnName("clien_uf");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("PlanejaAi.Models.Convidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("conv_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Confirmacao")
                        .HasColumnType("int")
                        .HasColumnName("conv_confirmacao");

                    b.Property<string>("Documento")
                        .HasColumnType("longtext")
                        .HasColumnName("conv_documento");

                    b.Property<int>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("even_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("conv_nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext")
                        .HasColumnName("conv_observacoes");

                    b.Property<string>("Token")
                        .HasColumnType("longtext")
                        .HasColumnName("conv_token");

                    b.HasKey("Id");

                    b.ToTable("convidados");
                });

            modelBuilder.Entity("PlanejaAi.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_cidade");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_cnpj");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("emp_data_cadastro");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_email");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_endereco");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("emp_nome");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_numero");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_status");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("emp_telefone");

                    b.HasKey("Id");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("PlanejaAi.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("even_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("clien_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("even_data");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_termino");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<int>("LocalTipo")
                        .HasColumnType("int")
                        .HasColumnName("even_local_tipo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("even_nome");

                    b.Property<string>("NomeLocalProprio")
                        .HasColumnType("longtext")
                        .HasColumnName("even_nome_local_proprio");

                    b.Property<int?>("ProdutoLocalId")
                        .HasColumnType("int")
                        .HasColumnName("even_produto_local_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("even_status");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext")
                        .HasColumnName("even_tipo");

                    b.Property<decimal>("ValorLocalProprio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("even_valor_local_proprio");

                    b.Property<decimal>("ValorTotalOrcamento")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("even_valor_total_orcamento");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoLocalId");

                    b.ToTable("eventos");
                });

            modelBuilder.Entity("PlanejaAi.Models.EventoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evit_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("even_id");

                    b.Property<string>("NomeExibicao")
                        .HasColumnType("longtext")
                        .HasColumnName("evit_nome_exibicao");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("prod_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("evit_quantidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("evit_status");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("evit_valor_custo");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("evit_valor_venda");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("evento_itens");
                });

            modelBuilder.Entity("PlanejaAi.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("forn_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("forn_cnpj_cpf");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("forn_data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("forn_email");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("forn_nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext")
                        .HasColumnName("forn_observacao");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("forn_status");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("forn_telefone");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("fornecedores");
                });

            modelBuilder.Entity("PlanejaAi.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("func_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext")
                        .HasColumnName("func_cargo");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext")
                        .HasColumnName("func_cpf");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("func_email");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("func_nome");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("PlanejaAi.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("log_acao");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("log_data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("log_descricao");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("evento_id");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("log_ip");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("log_tabela");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("log_usuario");

                    b.HasKey("Id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("PlanejaAi.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("login_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_data_cadastro");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("login_email");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int")
                        .HasColumnName("func_id");

                    b.Property<string>("PerfilAcesso")
                        .HasColumnType("longtext")
                        .HasColumnName("perfil_acesso");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext")
                        .HasColumnName("login_senha");

                    b.Property<string>("Token")
                        .HasColumnType("longtext")
                        .HasColumnName("login_token");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("login");
                });

            modelBuilder.Entity("PlanejaAi.Models.ProdutoFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prod_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("prod_ativo");

                    b.Property<int?>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("prod_data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("prod_descricao");

                    b.Property<int?>("FornecedorId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("forn_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("prod_nome");

                    b.Property<string>("Unidade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prod_unidade");

                    b.Property<decimal?>("ValorPadrao")
                        .IsRequired()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prod_valor_padrao");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("produtos_fornecedor");
                });

            modelBuilder.Entity("PlanejaAi.Models.CategoriaServico", b =>
                {
                    b.HasOne("PlanejaAi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PlanejaAi.Models.Cliente", b =>
                {
                    b.HasOne("PlanejaAi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PlanejaAi.Models.Evento", b =>
                {
                    b.HasOne("PlanejaAi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanejaAi.Models.ProdutoFornecedor", "ProdutoLocal")
                        .WithMany()
                        .HasForeignKey("ProdutoLocalId");

                    b.Navigation("Cliente");

                    b.Navigation("ProdutoLocal");
                });

            modelBuilder.Entity("PlanejaAi.Models.EventoItem", b =>
                {
                    b.HasOne("PlanejaAi.Models.Evento", "Evento")
                        .WithMany("EventoItens")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("PlanejaAi.Models.Fornecedor", b =>
                {
                    b.HasOne("PlanejaAi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PlanejaAi.Models.Funcionario", b =>
                {
                    b.HasOne("PlanejaAi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PlanejaAi.Models.Login", b =>
                {
                    b.HasOne("PlanejaAi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("PlanejaAi.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Empresa");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("PlanejaAi.Models.ProdutoFornecedor", b =>
                {
                    b.HasOne("PlanejaAi.Models.CategoriaServico", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanejaAi.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("PlanejaAi.Models.CategoriaServico", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PlanejaAi.Models.Evento", b =>
                {
                    b.Navigation("EventoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
